# Dockerfile.server

# Use a base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the necessary port
EXPOSE 4000 

# Start the server
CMD ["npm", "start", "dev"]

